version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - ./uploads:/app/uploads
      - ./processed:/app/processed
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
